CREATE TABLE `test`.`products2` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`product` VARCHAR( 20 ) NOT NULL ,
`description` TEXT NOT NULL ,
`source` VARCHAR( 20 ) NULL DEFAULT 'External',
`date_created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = MYISAM ;